      - name: Save images to separate tar files
        run: |
          docker save -o pinpoint-hbase.tar pinpointdocker/pinpoint-hbase:2.5.4
          docker save -o pinpoint-mysql.tar pinpointdocker/pinpoint-mysql:2.5.4
          docker save -o pinpoint-web.tar pinpointdocker/pinpoint-web:2.5.4
          docker save -o pinpoint-collector.tar pinpointdocker/pinpoint-collector:2.5.4
          docker save -o pinpoint-quickstart.tar pinpointdocker/pinpoint-quickstart
          docker save -o pinpoint-batch.tar pinpointdocker/pinpoint-batch:2.5.4
          docker save -o pinpoint-agent.tar pinpointdocker/pinpoint-agent:2.5.4
          docker save -o zookeeper.tar zookeeper:3.4.13
          docker save -o pinpoint-flink.tar pinpointdocker/pinpoint-flink:2.5.4

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pinpoint-arm64-images
          path: "*.tar"
          retention-days: 7
